// app.js
// Adjust this as more inputs from database are added
// !!! THIS FILE WAS NOT WRITTEN BY RUTH !!!
// Generated by ChatGPT
const NUM_DEPTHS = 11;

const BASE =
    "https://happyraindrop.github.io/Plenoptic_Image_Interactive_Refocuser/plenoptic_images_depth_slices";

const scenes =
{
    University_Processed:
        `${BASE}/University_Processed`,

    Chess:
        `${BASE}/Chess`
};

const canvas =
    document.getElementById("viewer");

const ctx =
    canvas.getContext("2d");

const sceneSelect =
    document.getElementById("sceneSelect");

const radiusSlider =
    document.getElementById("radiusSlider");

let currentScene = null;

let sharpImages = [];
let blurImages = [];

let chooserCanvas = null;
let chooserCtx = null;

let chooserWidth = 0;
let chooserHeight = 0;

let mouseX = 0.5;
let mouseY = 0.5;

let currentDepth = 0;

let imageWidth = 1;
let imageHeight = 1;

function resizeCanvas()
{
    canvas.width =
        window.innerWidth;

    canvas.height =
        window.innerHeight;

    draw();
}

window.addEventListener(
    "resize",
    resizeCanvas
);

function loadImage(url)
{
    return new Promise(
        (resolve,reject)=>
        {
            const img =
                new Image();

            img.crossOrigin =
                "anonymous";

            img.onload =
                ()=>resolve(img);

            img.onerror =
                reject;

            img.src =
                url;
        }
    );
}

async function loadScene(sceneName)
{
    const folder =
        scenes[sceneName];

    sharpImages = [];
    blurImages = [];

    for(let i=0;i<NUM_DEPTHS;i++)
    {
        const idx =
            String(i)
            .padStart(2,"0");

        sharpImages.push(
            loadImage(
                `${folder}/sharper-${idx}.png`
            )
        );

        blurImages.push(
            loadImage(
                `${folder}/blurred-${idx}.png`
            )
        );
    }

    const chooserImg =
        await loadImage(
            `${folder}/depth_chooser.png`
        );

    sharpImages =
        await Promise.all(
            sharpImages
        );

    blurImages =
        await Promise.all(
            blurImages
        );

    chooserCanvas =
        document.createElement(
            "canvas"
        );

    chooserCanvas.width =
        chooserImg.width;

    chooserCanvas.height =
        chooserImg.height;

    chooserCtx =
        chooserCanvas.getContext(
            "2d"
        );

    chooserCtx.drawImage(
        chooserImg,
        0,
        0
    );

    chooserWidth =
        chooserImg.width;

    chooserHeight =
        chooserImg.height;

    imageWidth =
        sharpImages[0].width;

    imageHeight =
        sharpImages[0].height;

    currentScene =
        sceneName;

    updateDepth();

    draw();
}

function updateDepth()
{
    if(!chooserCtx)
        return;

    const px =
        Math.max(
            0,
            Math.min(
                chooserWidth-1,
                Math.floor(
                    mouseX *
                    chooserWidth
                )
            )
        );

    const py =
        Math.max(
            0,
            Math.min(
                chooserHeight-1,
                Math.floor(
                    mouseY *
                    chooserHeight
                )
            )
        );

    const pixel =
        chooserCtx.getImageData(
            px,
            py,
            1,
            1
        ).data;

    currentDepth =
        Math.min(
            NUM_DEPTHS-1,
            pixel[0]
        );
}

function draw()
{
    if (sharpImages.length === 0)
        return;

    ctx.clearRect(
        0,
        0,
        canvas.width,
        canvas.height
    );

    const scale =
        Math.min(
            canvas.width / imageWidth,
            canvas.height / imageHeight
        ) * 0.95;

    const drawWidth =
        imageWidth * scale;

    const drawHeight =
        imageHeight * scale;

    const offsetX =
        (canvas.width - drawWidth) / 2;

    const offsetY =
        (canvas.height - drawHeight) / 2;

    const blur =
        blurImages[currentDepth];

    const sharp =
        sharpImages[currentDepth];

    // draw blurred image everywhere
    ctx.drawImage(
        blur,
        offsetX,
        offsetY,
        drawWidth,
        drawHeight
    );

    const screenX =
        offsetX +
        mouseX * drawWidth;

    const screenY =
        offsetY +
        mouseY * drawHeight;

    const radius =
        parseInt(
            radiusSlider.value
        );

    // clip a circle and draw sharp image inside it
    ctx.save();

    ctx.beginPath();

    ctx.arc(
        screenX,
        screenY,
        radius,
        0,
        Math.PI * 2
    );

    ctx.clip();

    ctx.drawImage(
        sharp,
        offsetX,
        offsetY,
        drawWidth,
        drawHeight
    );

    ctx.restore();
}

canvas.addEventListener(
    "mousemove",
    event =>
    {
        const rect =
            canvas.getBoundingClientRect();

        mouseX =
            (
                event.clientX -
                rect.left
            ) /
            rect.width;

        mouseY =
            (
                event.clientY -
                rect.top
            ) /
            rect.height;

        mouseX =
            Math.max(
                0,
                Math.min(
                    1,
                    mouseX
                )
            );

        mouseY =
            Math.max(
                0,
                Math.min(
                    1,
                    mouseY
                )
            );

        updateDepth();

        draw();
    }
);

radiusSlider.addEventListener(
    "input",
    draw
);

sceneSelect.addEventListener(
    "change",
    () =>
    {
        loadScene(
            sceneSelect.value
        );
    }
);

resizeCanvas();

loadScene(
    "University_Processed"
);